###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3"
name: "joints-muscles"
services:
  webserver:
    build: docker-images/apache
    container_name: joints-muscles-webserver
    working_dir: /application/
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ./docs:/application
      - ${SSH_AUTH_SOCK}:/ssh-agent
    ports:
      - "8000:80"
      - "8443:443"
